name = "Pyth scaled rebased prices oracle"
type = "PYTH"
url = "https://pyth.network"
description_markdown = """
# Pyth scaled rebased prices oracle

A simple contract providing scaled prices from the pyth on chain oracles quoted in USDT (reference implementation: https://github.com/vegaprotocol/pyth-rebase-contract)
"""

[oracle]
source_chain = "gnosis"
source_chain_id = "100"
type = "eth_address"
eth_address= "0x2BA6654FdB605637994047ecA217a02E224c4828"
status = "GOOD"
status_reason = ""
first_verified = 2024-06-25T00:00:00Z
last_verified = 2024-06-25T00:00:00Z

[[proofs]]
type = "web"
format = "url"
url = "https://gnosisscan.io/address/0x2BA6654FdB605637994047ecA217a02E224c4828#code"
available = true
